### ISSUE TITLE
cannot import as cjs

### ISSUE THREAD

**Issue by mbrevda** [pkolt/express-asyncify#10]
Just installed and I'm getting the following error:

```
/APP/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /APP/node_modules/express-asyncify/dist/cjs/index.js from /APP/index.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /APP/node_modules/express-asyncify/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at require.extensions.<computed> [as .js] (/APP/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/APP/index.ts:8:63)
    at m._compile (/APP/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/APP/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/APP/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/APP/node_modules/ts-node/dist/bin.js:54:12)
    at main (/APP/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/APP/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by pkolt** [comment]
Hi @mbrevda !

Thank you for your message 👍!

Can you check this error on the new version `2.0.2`? Also note if you are using CommonJS modules then your module import will look like this:

```js
const asyncify = require('express-asyncify').default;
```

Thanks!

**Comment by mbrevda** [comment]
yes, this seems great. Thanks!
